name: ewaste_manager
description: E-Waste Management App

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.2.1
  font_awesome_flutter: ^10.1.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.16.0
  google_sign_in: ^5.2.4
  cupertino_icons: ^1.0.6 
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  form_field_validator: ^1.1.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.4.0
  image_picker: ^1.0.1
  permission_handler: ^11.0.1
  provider: ^6.1.3
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutterfire_cli: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/email.png
    - assets/images/lock.png
    - assets/images/lock_login.png
    - assets/images/confirm_lock.png
    - assets/images/visibility.png
    - assets/images/visibility_off.png
    - assets/images/visibility_login.png
    - assets/images/visibility_off_login.png
    - assets/images/confirm_visibility.png
    - assets/images/confirm_visibility_off.png
    - assets/images/back.png
    - assets/images/app_logo.jpg
