// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW0PkAC4T7soUi07waMsru-giMooSIG8c',
    appId: '1:54882797991:web:18164649abceadb73b4e82',
    messagingSenderId: '54882797991',
    projectId: 'e-waste-management-9247d',
    authDomain: 'e-waste-management-9247d.firebaseapp.com',
    storageBucket: 'e-waste-management-9247d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgT_IEJC_n7bAzVJ4-XjBosK-J_1EbqOk',
    appId: '1:54882797991:android:6a1a54b0792ba7be3b4e82',
    messagingSenderId: '54882797991',
    projectId: 'e-waste-management-9247d',
    storageBucket: 'e-waste-management-9247d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOPtwjmYKvs2JpGGiEgXmmdlAG7ddaHDI',
    appId: '1:54882797991:ios:280c7d57c8c9ac363b4e82',
    messagingSenderId: '54882797991',
    projectId: 'e-waste-management-9247d',
    storageBucket: 'e-waste-management-9247d.firebasestorage.app',
    androidClientId: '54882797991-fahl5vka9sik6b39q7c28qgr4jp6d1po.apps.googleusercontent.com',
    iosClientId: '54882797991-hk4voup7uujspuqmjebcvl61mjlo9g61.apps.googleusercontent.com',
    iosBundleId: 'com.example.ewasteforme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOPtwjmYKvs2JpGGiEgXmmdlAG7ddaHDI',
    appId: '1:54882797991:ios:280c7d57c8c9ac363b4e82',
    messagingSenderId: '54882797991',
    projectId: 'e-waste-management-9247d',
    storageBucket: 'e-waste-management-9247d.firebasestorage.app',
    androidClientId: '54882797991-fahl5vka9sik6b39q7c28qgr4jp6d1po.apps.googleusercontent.com',
    iosClientId: '54882797991-hk4voup7uujspuqmjebcvl61mjlo9g61.apps.googleusercontent.com',
    iosBundleId: 'com.example.ewasteforme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW0PkAC4T7soUi07waMsru-giMooSIG8c',
    appId: '1:54882797991:web:e0fc010d8e293cd53b4e82',
    messagingSenderId: '54882797991',
    projectId: 'e-waste-management-9247d',
    authDomain: 'e-waste-management-9247d.firebaseapp.com',
    storageBucket: 'e-waste-management-9247d.firebasestorage.app',
  );

}